#pragma once
#include "pluginterfaces/base/funknown.h"

namespace Steinberg { namespace Vst {

// processor GUID
// {BDCB8A54-FFCB-4639-A045-9B7B3D3A36FF}
// generated by http://www.guidgenerator.com
static const FUID BLITSawProcessorID(0xBDCB8A54, 0xFFCB4639, 0xA0459B7B, 0x3D3A36FF);

// controller GUID
// {5C69CE5D-8222-47E4-833F-DD97CFCD5876}
// (generated by http://www.guidgenerator.com)
static const FUID BLITSawControllerID(0x5C69CE5D, 0x822247E4, 0x833FDD97, 0xCFCD5876);

}} // namespace
